# config/spark-defaults.conf

# ------------------------------------------------------------
# Spark master
# ------------------------------------------------------------
spark.master spark://spark-master:7077

# ------------------------------------------------------------
# Python configuration for Bitnami Spark image
# ------------------------------------------------------------
spark.pyspark.python /opt/bitnami/python/bin/python
spark.pyspark.driver.python /opt/bitnami/python/bin/python

# ------------------------------------------------------------
# Delta Lake integration
# Required for reading/writing Delta tables:
# Bronze Delta, Silver Delta, Gold Delta
# ------------------------------------------------------------
spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.sql.catalogImplementation in-memory

# ------------------------------------------------------------
# Required packages
#
# delta-spark:
# Enables Delta Lake support.
# postgresql:
# Allows Spark to write/read PostgreSQL tables via JDBC.
# spark-sql-kafka:
# Allows Spark Structured Streaming to read from Redpanda/Kafka.
# ------------------------------------------------------------
spark.jars.packages io.delta:delta-spark_2.12:3.2.0,org.postgresql:postgresql:42.7.4,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1

# ------------------------------------------------------------
# Persistent Ivy cache
#
# This path matches the Docker Compose volume:
# spark_ivy_cache:/opt/bitnami/spark/ivy
# This avoids downloading Spark packages every time.
# ------------------------------------------------------------
spark.jars.ivy /opt/bitnami/spark/ivy

# ------------------------------------------------------------
# Resource defaults for local POC
# ------------------------------------------------------------
spark.cores.max 1
spark.executor.cores 1
spark.executor.memory 1g

# ------------------------------------------------------------
# SQL / performance defaults
# ------------------------------------------------------------
spark.sql.shuffle.partitions 4
spark.sql.adaptive.enabled true
spark.sql.session.timeZone Europe/Paris

# ------------------------------------------------------------
# Spark temporary files
#
# This is separate from Ivy cache.
# It is used for Spark temporary execution files.
# ------------------------------------------------------------
spark.local.dir /opt/bitnami/spark/tmp